import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <nav style={{ display: "flex", gap: 12, padding: 16, borderBottom: "1px solid #222" }}>
          <a href="/">Browse</a>
          <a href="/connect">Connect node</a>
          <a href="/upload">Upload</a>
          <a href="/register">Register</a>
        </nav>
        {children}
      </body>
    </html>
  );
}
